services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin # Usuário do banco
      POSTGRES_PASSWORD: admin123 # Senha do usuário
      POSTGRES_DB: loja # Nome do banco inicial
    ports:
      - '5432:5432' # Porta exposta no host
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistência dos dados
    networks:
      - postgres-network

volumes:
  postgres-data: # Volume para persistência dos dados

networks:
  postgres-network: # Rede para comunicação entre serviços
